server:
  port: 9105

spring:
  application:
    name: quickstart


app:
  url:
    host: http://localhost:9105/
    host2: http://localhost:9105/
    prefix: /backend/v1


logging:
  level:
    root: info
    io.github.liuziyuan: debug

