server:
  port: 9115

spring:
  application:
    name: inherit

app:
  hello:
    url: http://localhost:9100/


logging:
  level:
    root: info
    io.github.easyretrofit: debug

retrofit:
  timelimiter:
    configs:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        write-timeout: 5000
    instances:
      errorTimeout:
        base-config: default


