server:
  port: 9106

spring:
  application:
    name: global


app:
  url:
    host: http://localhost:9100/
    prefix: /backend/v1

okhttpclient:
  timeout: 30000

logging:
  level:
    root: info
    io.github.easyretrofit: debug

retrofit:
  global:
    builder:
      enable-global: true
      converter-factory-builder-clazz: io.github.liuziyuan.retrofit.samples.global.config.api.GsonConvertFactoryBuilder
      call-adapter-factory-builder-clazz: io.github.liuziyuan.retrofit.samples.global.config.api.RxJavaCallAdapterFactoryBuilder
