spring.application.name: okhttp-sentinal
server.port: 9300

logging:
  level:
    root: info
    io.github.liuziyuan.retrofit: debug

retrofit:
  sentinel:
    degrade:
      configs:
        default:
          #设置熔断触发的最小请求数(count)为 1 设置熔断触发的时间窗口(timeWindow)为 20s 设置熔断触发的降级比例阈值(slowRatioThreshold)为 100%
          count: 1
          timeWindow: 20
          slowRatioThreshold: 1.0
          grade: 2
      instances:
        helloDegrade:
          base-config: default