server:
  port: 9110

spring:
  application:
    name: quickstart


app:
  url:
    host: http://localhost:9100/
    host2: http://localhost:9100/
    prefix: /v1


logging:
  level:
    root: info
    io.github.liuziyuan: debug

retrofit:
  global:
    enable: true
    base-url: ${app.url.host2}
    converter-factory-builder-clazz: io.github.liuziyuan.retrofit.spring.boot.web.JacksonConvertFactoryBuilder
    call-adapter-factory-builder-clazz: io.github.liuziyuan.retrofit.spring.boot.web.BodyCallAdapterFactoryBuilder

