server:
  port: 9104

spring:
  application:
    name: single-instance

app:
  hello:
    v1:
      url: http://localhost:9100/backend/v1
    v2:
      url: http://localhost:9100/backend/v2

okhttpclient:
  timeout: 30000