server:
  port: 9107

spring:
  application:
    name: dynamic-url


app:
  url:
    host: http://localhost:9100/
    host-dynamic: http://localhost:9200/
    prefix: /backend/v1


logging:
  level:
    root: info
    io.github.easyretrofit: debug

